require File.expand_path('../spec_helper.rb', __FILE__)

describe SettingsPlistGenerator = CocoaPodsAcknowledgements::SettingsPlistGenerator do

  before do
    @spec1 = Pod::Specification.new do |s|
      s.name = 'monkeylib'
      s.version = '1.0'
      s.authors = {
        'CocoaPods' => 'email@cocoapods.org'
      }
      s.social_media_url = 'https://twitter.com/CocoaPods'
      s.homepage = 'https://github.com/CocoaPods/monkeylib'
      s.license = {
        :type => 'MIT',
        :file => 'LICENSE',
        :text => 'Permission is hereby granted ...'
      }
      s.summary = 'A lib to do monkey things'
      s.description = <<EOF
## What is it
A lib to do monkey things
## Why?
Why not?
EOF
    end
    @spec2 = Pod::Specification.new do |s|
      s.name         = 'BananaLib'
      s.version      = '1.0'
      s.authors      = 'Banana Corp', { 'Monkey Boy' => 'monkey@banana-corp.local' }
      s.homepage     = 'http://banana-corp.local/banana-lib.html'
      s.summary      = 'Chunky bananas!'
      s.description  = 'Full of chunky bananas.'
      s.source       = { :git => 'http://banana-corp.local/banana-lib.git', :tag => 'v1.0' }
      s.license      = {
        :type => 'MIT',
        :file => 'LICENSE',
        :text => 'Permission is hereby granted ...'
      }
      s.source_files        = 'Classes/*.{h,m,d}', 'Vendor', 'framework/Source/*.h'
      s.resources           = "Resources/*", "Resources/Images.xcassets"
      s.vendored_framework  = 'BananaFramework.framework'
      s.vendored_library    = 'libBananaStaticLib.a'
      s.preserve_paths      = 'preserve_me.txt'
      s.public_header_files = 'Classes/Banana.h', 'framework/Source/MoreBanana.h'
      s.module_map          = 'Banana.modulemap'

      s.prefix_header_file = 'Classes/BananaLib.pch'
      s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-framework SystemConfiguration' }
      s.dependency   'monkey', '~> 1.0.1', '< 1.0.9'
    end
    SettingsPlistGenerator.stubs(:file_accessor).returns(nil)
    @sandbox = temporary_sandbox
    @target_description = stub('target_description',
                               :specs => [@spec1, @spec2],
                               :platform_name => 'ios')
  end

  it 'generates metadata' do
    result = SettingsPlistGenerator.generate(@target_description, @sandbox, [])
    result.should == {
      'Title' => 'Acknowledgements',
      'StringsTable' => 'Acknowledgements',
      'PreferenceSpecifiers' => [
        {
          'Title' => 'Acknowledgements',
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'This application makes use of the following third party libraries:'
        },
        {
          'Title' => 'monkeylib',
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'Permission is hereby granted ...'
        },
        {
          'Title' => 'BananaLib',
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'Permission is hereby granted ...'
        },
        {
          'Title' => nil,
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'Generated by CocoaPods - https://cocoapods.org'
        },
      ]
    }
  end

  it 'generates nil if specs is empty' do
    target_description = stub('target_description',
                              :specs => [],
                              :platform_name => 'ios')
    result = SettingsPlistGenerator.generate(target_description, @sandbox, [])
    result.should.be.nil?
  end

  it 'does not include metadata for excluded specs' do
    target_description = stub('target_description',
                              :specs => [@spec1, @spec2],
                              :platform_name => 'ios')
    result = SettingsPlistGenerator.generate(target_description, @sandbox, [@spec1.name])
    result.should == {
      'Title' => 'Acknowledgements',
      'StringsTable' => 'Acknowledgements',
      'PreferenceSpecifiers' => [
        {
          'Title' => 'Acknowledgements',
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'This application makes use of the following third party libraries:'
        },
        {
          'Title' => 'BananaLib',
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'Permission is hereby granted ...'
        },
        {
          'Title' => nil,
          'Type' => 'PSGroupSpecifier',
          'FooterText' => 'Generated by CocoaPods - https://cocoapods.org'
        },
      ]
    }
  end
end
