source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.2'

def targetName
    'example_project'
end

target targetName do

    # network
    pod 'AFNetworking'

    # logging
    pod 'CocoaLumberjack'

	plugin 'cocoapods-acknowledgements'
end